title: Two
use_meta_keywords: false
no_index_page: false
no_follow_links: false
sitemap_priority: '0.5'
sitemap_changefreq: daily
override_twitter_settings: false
updated_by: 998e47b6-651e-4252-b7ed-565ea3f20a95
updated_at: 1670591688
blueprint: category
